[theme]
primaryColor="#4CAF50"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F5"
textColor="#31333F"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats=false
